Command `sandbox publish`:
Command `sandbox run storage/0x00000000000000000000000000000002/modules/Test.mv --signers 0x1234abcd -v publish`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 0000000000000000000000001234ABCD:
    Added type 0x2::Test::Resource: [10, 0, 0, 0, 0, 0, 0, 0] (wrote 40 bytes)
      key 0x2::Test::Resource {
          i: 10
      }
Wrote 40 bytes of resource ID's and data
