Command `sandbox publish`:
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xB56982FCEAF6B87DE12E6BF3BF28FEE7 --args 10471647352579929704 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address B56982FCEAF6B87DE12E6BF3BF28FEE7:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [104, 182, 175, 55, 201, 195, 82, 145] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 10471647352579929704
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x733774F48EE26B36A72A2F4E2C7619D8 --args 0 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 733774F48EE26B36A72A2F4E2C7619D8:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [0, 0, 0, 0, 0, 0, 0, 0] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 0
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x1B8D1F57AB4C18F95DBBF47E7EFC378D --args 1 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 1B8D1F57AB4C18F95DBBF47E7EFC378D:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [1, 0, 0, 0, 0, 0, 0, 0] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 1
          }
      }
Wrote 82 bytes of resource ID's and data
