Command `sandbox publish`:
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xB56982FCEAF6B87DE12E6BF3BF28FEE7 --args 10471647352579929704 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address B56982FCEAF6B87DE12E6BF3BF28FEE7:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [104, 182, 175, 55, 201, 195, 82, 145] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 10471647352579929704
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xE618BC8AADFE1312FE23ED15FBAFE258 --args 10032507486942512966 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address E618BC8AADFE1312FE23ED15FBAFE258:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [70, 199, 167, 165, 103, 160, 58, 139] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 10032507486942512966
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x61A53B2A5A5C12566841B87753D72334 --args 3855442051891407440 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 61A53B2A5A5C12566841B87753D72334:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [80, 42, 23, 131, 30, 72, 129, 53] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 3855442051891407440
          }
      }
Wrote 82 bytes of resource ID's and data
