Command `sandbox publish`:
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xB56982FCEAF6B87DE12E6BF3BF28FEE7 --args 10471647352579929704 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address B56982FCEAF6B87DE12E6BF3BF28FEE7:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [104, 182, 175, 55, 201, 195, 82, 145] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 10471647352579929704
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x733774F48EE26B36A72A2F4E2C7619D8 --args 0 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 733774F48EE26B36A72A2F4E2C7619D8:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [0, 0, 0, 0, 0, 0, 0, 0] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 0
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x18DFFF6E15E41BA68599F5731ADCDA46 --args 18446744073709551615 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 18DFFF6E15E41BA68599F5731ADCDA46:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [255, 255, 255, 255, 255, 255, 255, 255] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 18446744073709551615
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x5DC645E99FF9EB99EBDC1D23D4E1E92B --args 16645234943703539872 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 5DC645E99FF9EB99EBDC1D23D4E1E92B:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [160, 96, 94, 182, 253, 192, 255, 230] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 16645234943703539872
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xF3F7C5FC9AEAEBB3D9FAD8F5A8C64519 --args 0xE4B73D54744F154E5FAD8F39DD9C82AB 2064412762981130635 -v transfer`:
Execution failed because of a RESOURCE_DOES_NOT_EXIST error (i.e., `move_from<T>(a)`, `borrow_global<T>(a)`, or `borrow_global_mut<T>(a)` when there is no resource of type `T` at address `a`) in 0000000000000000000000000000CAFE::BasicCoin::balance_of at code offset 1
