Command `sandbox publish`:
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xB56982FCEAF6B87DE12E6BF3BF28FEE7 --args 10471647352579929704 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address B56982FCEAF6B87DE12E6BF3BF28FEE7:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [104, 182, 175, 55, 201, 195, 82, 145] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 10471647352579929704
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x733774F48EE26B36A72A2F4E2C7619D8 --args 0 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 733774F48EE26B36A72A2F4E2C7619D8:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [0, 0, 0, 0, 0, 0, 0, 0] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 0
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xFA4B7AB6F8F1AEEDA89AB22DE345147F --args 17390408797090421340 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address FA4B7AB6F8F1AEEDA89AB22DE345147F:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [92, 26, 103, 161, 169, 36, 87, 241] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 17390408797090421340
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x6273B838CEDBEEECA356C9C3D25E1E83 --args 15559842344388822660 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 6273B838CEDBEEECA356C9C3D25E1E83:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [132, 134, 96, 50, 44, 170, 239, 215] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 15559842344388822660
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x5972884437EE261232E5D1B65CDEBB87 --args 18446744073709551615 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 5972884437EE261232E5D1B65CDEBB87:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [255, 255, 255, 255, 255, 255, 255, 255] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 18446744073709551615
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xA1FADD69BD2FA8DAC2A5679B1F8F16E5 --args 0 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address A1FADD69BD2FA8DAC2A5679B1F8F16E5:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [0, 0, 0, 0, 0, 0, 0, 0] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 0
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xA727DC376F47CDBE3B77CFF737ACE4CD --args 1 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address A727DC376F47CDBE3B77CFF737ACE4CD:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [1, 0, 0, 0, 0, 0, 0, 0] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 1
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0x91CEFE843AF1ABCF431757214E983F71 --args 9317870137442859375 -v setup_and_mint`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address 91CEFE843AF1ABCF431757214E983F71:
    Added type 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin>: [111, 121, 128, 149, 133, 185, 79, 129] (wrote 82 bytes)
      key 0xcafe::BasicCoin::Balance<0xcafe::MyOddCoin::MyOddCoin> {
          coin: store 0xcafe::BasicCoin::Coin<0xcafe::MyOddCoin::MyOddCoin> {
              value: 9317870137442859375
          }
      }
Wrote 82 bytes of resource ID's and data
Command `sandbox run storage/0x0000000000000000000000000000CAFE/modules/MyOddCoin.mv --signers 0xD2BF6C1F1334DF3BAF6117BAC23456D4 --args 0x9716ECBF22228D2914B443AF168C1383 11470264690596131617 -v transfer`:
Execution failed because of a RESOURCE_DOES_NOT_EXIST error (i.e., `move_from<T>(a)`, `borrow_global<T>(a)`, or `borrow_global_mut<T>(a)` when there is no resource of type `T` at address `a`) in 0000000000000000000000000000CAFE::BasicCoin::balance_of at code offset 1
