Command `sandbox publish`:
Command `sandbox run storage/0x00000000000000000000000000000002/modules/Test.mv --signers 0x1234abcd -v unpublish`:
Execution failed because of a RESOURCE_DOES_NOT_EXIST error (i.e., `move_from<T>(a)`, `borrow_global<T>(a)`, or `borrow_global_mut<T>(a)` when there is no resource of type `T` at address `a`) in 00000000000000000000000000000002::Test::unpublish at code offset 2
