Command `sandbox publish`:
Command `sandbox run storage/0x00000000000000000000000000000002/modules/Test.mv --signers 0xA7DCDBE3692CE95C3BC1BA1DB15C616E -v publish`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address A7DCDBE3692CE95C3BC1BA1DB15C616E:
    Added type 0x2::Test::Resource: [10, 0, 0, 0, 0, 0, 0, 0] (wrote 40 bytes)
      key 0x2::Test::Resource {
          i: 10
      }
Wrote 40 bytes of resource ID's and data
Command `sandbox run storage/0x00000000000000000000000000000002/modules/Test.mv --signers 0xD6BFEA3E764147A78669553DBDD312F4 -v unpublish`:
Execution failed because of a RESOURCE_DOES_NOT_EXIST error (i.e., `move_from<T>(a)`, `borrow_global<T>(a)`, or `borrow_global_mut<T>(a)` when there is no resource of type `T` at address `a`) in 00000000000000000000000000000002::Test::unpublish at code offset 2
