Command `sandbox publish`:
Command `sandbox run storage/0x00000000000000000000000000000002/modules/Test.mv --signers 0xA7DCDBE3692CE95C3BC1BA1DB15C616E -v publish`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address A7DCDBE3692CE95C3BC1BA1DB15C616E:
    Added type 0x2::Test::Resource: [10, 0, 0, 0, 0, 0, 0, 0] (wrote 40 bytes)
      key 0x2::Test::Resource {
          i: 10
      }
Wrote 40 bytes of resource ID's and data
Command `sandbox run storage/0x00000000000000000000000000000002/modules/Test.mv --signers 0xA7DCDBE3692CE95C3BC1BA1DB15C616E --args 1 -v write`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address A7DCDBE3692CE95C3BC1BA1DB15C616E:
    Changed type 0x2::Test::Resource: [11, 0, 0, 0, 0, 0, 0, 0] (wrote 40 bytes)
         key 0x2::Test::Resource {
-            i: 10
+            i: 11
         }
Wrote 40 bytes of resource ID's and data
Command `sandbox run storage/0x00000000000000000000000000000002/modules/Test.mv --signers 0xA7DCDBE3692CE95C3BC1BA1DB15C616E -v unpublish`:
Changed resource(s) under 1 address(es):
  Changed 1 resource(s) under address A7DCDBE3692CE95C3BC1BA1DB15C616E:
    Deleted type 0x2::Test::Resource (wrote 32 bytes)
      key 0x2::Test::Resource {
          i: 11
      }
Wrote 32 bytes of resource ID's and data
